name: Diff & Apply Patch

on:
  workflow_dispatch:
    inputs:
      repo_a:
        description: 'Repo A (contoh: user/repo-a)'
        required: true
        default: 'user/repo-a'
      branch_a:
        description: 'Branch di Repo A'
        required: true
        default: 'main'
      repo_b:
        description: 'Repo B (contoh: user/repo-b)'
        required: true
        default: 'user/repo-b'
      branch_b:
        description: 'Branch di Repo B'
        required: true
        default: 'main'

jobs:
  diff-and-apply:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # supaya bisa push branch baru
      pull-requests: write  # supaya bisa bikin PR

    steps:
      # 1. Checkout Repo A (target patch)
      - name: Checkout Repo A
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo_a }}
          ref: ${{ github.event.inputs.branch_a }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: repo-a

      # 2. Checkout Repo B (sumber patch)
      - name: Checkout Repo B
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo_b }}
          ref: ${{ github.event.inputs.branch_b }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: repo-b

      # 3. Buat patch
      - name: Generate patch
        run: |
          diff -ruN repo-a repo-b > changes.patch || true
          echo "Patch dibuat: $(wc -l < changes.patch) baris"

      # 4. Terapkan patch ke Repo A
      - name: Apply patch
        working-directory: repo-a
        run: |
          cp ../changes.patch .
          patch --batch -p1 < changes.patch || true
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 5. Commit & push ke branch baru
      - name: Commit & Push changes
        working-directory: repo-a
        run: |
          git checkout -b apply-patch-${{ github.run_id }}
          git add -A
          if git diff --cached --quiet; then
            echo "⚠️ Tidak ada perubahan setelah patch"
            exit 0
          fi
          git commit -m "Apply patch from ${{ github.event.inputs.repo_b }} (${{ github.event.inputs.branch_b }})"
          git push origin apply-patch-${{ github.run_id }}

      # 6. Buat Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.inputs.repo_a }}
          base: ${{ github.event.inputs.branch_a }}
          branch: apply-patch-${{ github.run_id }}
          title: "Apply patch from ${{ github.event.inputs.repo_b }}:${{ github.event.inputs.branch_b }}"
          body: |
            This PR applies a patch generated by diff between:

            - **${{ github.event.inputs.repo_a }} [${{ github.event.inputs.branch_a }}]**
            - **${{ github.event.inputs.repo_b }} [${{ github.event.inputs.branch_b }}]**

            ⚙️ Generated automatically by GitHub Actions.
