name: notif kernel multi6

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Cek versi kernel
        shell: bash
        run: |
          set -e
          URLS=("https://raw.githubusercontent.com/unifreq/linux-6.12.y/main/Makefile"
                "https://raw.githubusercontent.com/unifreq/linux-6.6.y/main/Makefile")

          mkdir -p data/kernel
          CHAT_IDS=($(echo "${{ secrets.TELEGRAM_CHAT_ID }}" | tr ',' '\n' | sort -u))
          RELEASE_URL="https://github.com/tes-rep/kernel/releases"

          for URL in "${URLS[@]}"; do
            NAME=$(echo $URL | grep -oP 'linux-\d+\.\d+\.y')
            FILE="data/kernel/$NAME.txt"

            CONTENT=$(curl -s $URL)
            VERSION=$(echo "$CONTENT" | grep -oP '(?<=VERSION = )\d+')
            PATCHLEVEL=$(echo "$CONTENT" | grep -oP '(?<=PATCHLEVEL = )\d+')
            SUBLEVEL=$(echo "$CONTENT" | grep -oP '(?<=SUBLEVEL = )\d+')
            LATEST_VER="$VERSION.$PATCHLEVEL.$SUBLEVEL"

            if [ -f $FILE ]; then
              OLD_VER=$(cat $FILE)
            else
              OLD_VER="tidak tersedia"
            fi

            if [ "$OLD_VER" != "$LATEST_VER" ]; then
              echo "$LATEST_VER" > $FILE
              git add $FILE
              MSG="⚡ <b>Versi baru tersedia</b>
              ═══════════════════════
              📌 <b>Versi baru:</b> v$LATEST_VER
              📌 <b>Versi lama:</b> $OLD_VER
              📌 <b>Link release:</b> <a href='$RELEASE_URL'>Klik di sini</a>
              ═══════════════════════
             Silakan build kernel..."
            else
              MSG="ℹ️ <b>kernel $NAME tidak ada versi baru</b>
              ═══════════════════════
              📌 <b>Versi terakhir:</b> v$LATEST_VER
              ═══════════════════════
              📌 <b>Link release:</b> <a href='$RELEASE_URL'>Klik di sini</a>"
            fi

            for CHAT_ID in "${CHAT_IDS[@]}"; do
              curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
                -d chat_id="$CHAT_ID" \
                -d text="$MSG" \
                -d parse_mode="HTML" \
                -d disable_web_page_preview=true
            done
          done

      - name: Commit perubahan versi
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -m "Update versi kernel" --quiet || true
          git pull --rebase --quiet || true
          git push --quiet || true

      - name: Cek commit terbaru
        shell: bash
        run: |
          set -e
          URLS=("https://raw.githubusercontent.com/unifreq/linux-6.12.y/main/Makefile"
                "https://raw.githubusercontent.com/unifreq/linux-6.6.y/main/Makefile")

          mkdir -p data/kernel
          CHAT_IDS=($(echo "${{ secrets.TELEGRAM_CHAT_ID }}" | tr ',' '\n' | sort -u))


          for URL in "${URLS[@]}"; do
            NAME=$(echo $URL | grep -oP 'linux-\d+\.\d+\.y')
            FILE_COMMIT="data/kernel/$NAME.commit"
            REPO=$(echo $URL | grep -oP 'unifreq/linux-[0-9]+\.[0-9]+\.y')

            COMMIT_JSON=$(curl -s "https://api.github.com/repos/$REPO/commits?per_page=1")
            LATEST_COMMIT=$(echo "$COMMIT_JSON" | grep -oP '"sha": "\K[0-9a-f]+' | head -n1)
            COMMIT_MSG=$(echo "$COMMIT_JSON" | grep -oP '"message": "\K[^"]+' | head -n1)
            COMMIT_AUTHOR=$(echo "$COMMIT_JSON" | grep -oP '"name": "\K[^"]+' | head -n1)
            # Ambil commit date dari API GitHub
            COMMIT_DATE=$(echo "$COMMIT_JSON" | jq -r '.[0].commit.committer.date')

            # Konversi ke WIB
            COMMIT_DATE_WIB=$(TZ="Asia/Jakarta" date -d "$COMMIT_DATE" '+%d-%m-%Y %H:%M:%S WIB')


            if [ -f $FILE_COMMIT ]; then
              OLD_COMMIT=$(cat $FILE_COMMIT)
            else
              OLD_COMMIT="tidak ada"
            fi

            if [ "$LATEST_COMMIT" != "$OLD_COMMIT" ]; then
              echo "$LATEST_COMMIT" > $FILE_COMMIT
              git add $FILE_COMMIT
              MSG="🆕 <b>Commit baru terdeteksi</b>
              ═══════════════════════
              📌 <b>Kernel:</b> $NAME
              📌 <b>Commit:</b> <a href='https://github.com/$REPO/commit/$LATEST_COMMIT'>$LATEST_COMMIT</a>
              📌 <b>Author:</b> $COMMIT_AUTHOR
              📌 <b>Tanggal:</b> $COMMIT_DATE_WIB
              ═══════════════════════
              💬 <b>Message:</b> $COMMIT_MSG"
            else
              MSG="ℹ️ <b>$NAME tidak ada commit baru</b>
              ═══════════════════════
              📌 <b>Commit terakhir:</b> <a href='https://github.com/$REPO/commit/$LATEST_COMMIT'>$LATEST_COMMIT</a>
              ═══════════════════════
              💬 <b>Message:</b> $COMMIT_MSG"
            fi

            for CHAT_ID in "${CHAT_IDS[@]}"; do
              curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
                -d chat_id="$CHAT_ID" \
                -d text="$MSG" \
                -d parse_mode="HTML" \
                -d disable_web_page_preview=true
            done
          done

      - name: Commit perubahan commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -m "Update commit kernel" --quiet || true
          git pull --rebase --quiet || true
          git push --quiet || true

       # --- Notifikasi Commit ---
      - name: Cek Commit Terbaru
        shell: bash
        run: |
          # Ambil commit terbaru
          REPO="vernesong/mihomo"
          BRANCH="Alpha"

          # Buat folder data untuk simpan info versi
          mkdir -p data/mihomo

          # Konversi tanggal ke WIB
          COMMIT_DATE_WIB=$(date -d "$COMMIT_DATE_RAW +7 hours" '+%d-%m-%Y %H:%M:%S WIB')

          # Ambil commit terbaru dari branch dev
          COMMIT_JSON=$(curl -s "https://api.github.com/repos/$REPO/commits?per_page=1&sha=$BRANCH")

          LATEST_COMMIT=$(echo "$COMMIT_JSON" | grep -oP '"sha": "\K[0-9a-f]+' | head -n1)
          COMMIT_MSG=$(echo "$COMMIT_JSON" | grep -oP '"message": "\K[^"]+' | head -n1)
          COMMIT_AUTHOR=$(echo "$COMMIT_JSON" | grep -oP '"name": "\K[^"]+' | head -n1)
          COMMIT_DATE=$(echo "$COMMIT_JSON" | grep -oP '"date": "\K[^"]+' | head -n1)
          COMMIT_URL="https://github.com/$REPO/commit/$LATEST_COMMIT"

          if [ -z "$LATEST_COMMIT" ]; then
            echo "⚠️ Gagal ambil commit dari $REPO"
            exit 1
          fi

          if [ -f data/mihomo/last_commit.sha ]; then
            OLD_COMMIT=$(cat data/mihomo/last_commit.sha)
          else
            OLD_COMMIT=""
          fi

          if [ "$LATEST_COMMIT" != "$OLD_COMMIT" ]; then
            # Simpan commit terbaru
            echo "$LATEST_COMMIT" > data/mihomo/last_commit.sha
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add data/mihomo/last_commit.sha
            git commit -m "Update last_commit.sha ke $LATEST_COMMIT" --quiet || true
            git pull --rebase --quiet || true
            git push --quiet || true

            # Kirim Notifikasi Commit ke Telegram
            COMMIT_MSG=$(echo "$COMMIT_MSG" | sed 's/\&/\\&/g')
            MSG="🆕 <b>mihomo Commit baru terdeteksi</b>
            ═══════════════════════
            📌 <b>Commit:</b> <a href='$COMMIT_URL'>$LATEST_COMMIT</a>
            📌 <b>Author:</b> $COMMIT_AUTHOR
            📌 <b>Tanggal:</b> $COMMIT_DATE_WIB
            ────────────────────────
            💬 <b>Message:</b> $COMMIT_MSG"

          else
          # Versi baru terdeteksi → notif build dimulai
            MSG="🆕 <b>mihomo tidak ada Commit baru</b>
            ═══════════════════════
            📌 <b>Commit lama:</b> <a href='$COMMIT_URL'>$LATEST_COMMIT</a>
            📌 <b>Author:</b> $COMMIT_AUTHOR
            📌 <b>Tanggal:</b> $COMMIT_DATE_WIB
            ═══════════════════════
            💬 <b>Message:</b> $COMMIT_MSG"

          fi  

            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
              -d text="$MSG" \
              -d parse_mode="HTML" \
              -d disable_web_page_preview=true
                     
