name: notif kernel multi

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Cek beberapa versi dan notif Telegram
        shell: bash
        run: |
          # Daftar URL Makefile kernel berbeda
          URLS=("https://raw.githubusercontent.com/unifreq/linux-6.12.y/main/Makefile"
                "https://raw.githubusercontent.com/unifreq/linux-6.6.y/main/Makefile")

          # Array chat_id Telegram (hilangkan duplikat jika ada)
          CHAT_IDS=($(echo "${{ secrets.TELEGRAM_CHAT_IDS }}" | tr ',' '\n' | sort -u))

          for URL in "${URLS[@]}"; do
            NAME=$(basename $(dirname $URL))

            # Ambil konten Makefile
            CONTENT=$(curl -s $URL)
            if [ -z "$CONTENT" ]; then
              echo "⚠️ Gagal ambil $URL, lewati..."
              continue
            fi

            # Ambil versi terbaru
            LATEST_VER=$(echo "$CONTENT" | grep -oP '(?<=SUBLEVEL =)[0-9\.]+')
            if [ -z "$LATEST_VER" ]; then
              echo "⚠️ Versi tidak ditemukan di $URL, lewati..."
              continue
            fi

            # Ambil versi lama
            FILE="$NAME.txt"
            if [ -f $FILE ]; then
              OLD_VER=$(cat $FILE)
            else
              OLD_VER="tidak tersedia"
            fi

            # Tentukan status build
            if [ "$OLD_VER" != "$LATEST_VER" ]; then
              echo "$LATEST_VER" > $FILE
              git config user.name "github-actions"
              git config user.email "actions@github.com"
              git add $FILE
              git commit -m "Update $FILE ke $LATEST_VER" --quiet || true
              git pull --rebase --quiet || true
              git push --quiet || true

              MSG="⚡ <b>Build $NAME dimulai...</b>
              ═══════════════════════
              📌 <b>Versi baru:</b> v$LATEST_VER
              📌 <b>Versi lama:</b> $OLD_VER
               ═══════════════════════
              Harap tunggu beberapa menit 🚀"
            else
              MSG="ℹ️ <b>$NAME tidak ada versi baru</b>
            Versi terakhir: v$LATEST_VER"
            fi

            # Kirim notif ke semua chat_id unik
            for CHAT_ID in "${CHAT_IDS[@]}"; do
              curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
                -d chat_id="$CHAT_ID" \
                -d text="$MSG" \
                -d parse_mode="HTML"
            done
          done
