name: notif kernel multi

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Cek beberapa versi dan notif Telegram
        shell: bash
        run: |
          # Daftar URL Makefile kernel berbeda
          URLS=("https://raw.githubusercontent.com/unifreq/linux-6.12.y/main/Makefile"
                "https://raw.githubusercontent.com/unifreq/linux-6.6.y/main/Makefile")

          # Ambil chat_id Telegram, hilangkan duplikat
          if [ -z "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
            echo "❌ Secret TELEGRAM_CHAT_ID kosong, hentikan workflow"
            exit 1
          fi
          CHAT_IDS=($(echo "${{ secrets.TELEGRAM_CHAT_ID }}" | tr ',' '\n' | sort -u))

          # URL release kernel
          RELEASE_URL="https://github.com/tes-rep/kernel/releases"

          for URL in "${URLS[@]}"; do
            # Buat identifier unik per kernel
            NAME=$(echo $URL | grep -oP 'linux-\d+\.\d+\.y')
            FILE="$NAME.txt"

            # Ambil konten Makefile
            CONTENT=$(curl -s $URL)
            if [ -z "$CONTENT" ]; then
              echo "⚠️ Gagal ambil $URL, lewati..."
              continue
            fi

            # Ambil versi lengkap kernel
            VERSION=$(echo "$CONTENT" | grep -oP '(?<=VERSION = )\d+')
            PATCHLEVEL=$(echo "$CONTENT" | grep -oP '(?<=PATCHLEVEL = )\d+')
            SUBLEVEL=$(echo "$CONTENT" | grep -oP '(?<=SUBLEVEL = )\d+')
            LATEST_VER="$VERSION.$PATCHLEVEL.$SUBLEVEL"
            if [ -z "$VERSION" ] || [ -z "$PATCHLEVEL" ] || [ -z "$SUBLEVEL" ]; then
              echo "⚠️ Versi tidak lengkap di $URL, lewati..."
              continue
            fi

            # Ambil versi lama
            if [ -f $FILE ]; then
              OLD_VER=$(cat $FILE)
            else
              OLD_VER="tidak tersedia"
            fi

            # Tentukan status build / notif
            if [ "$OLD_VER" != "$LATEST_VER" ]; then
              echo "$LATEST_VER" > $FILE
              git config user.name "github-actions"
              git config user.email "actions@github.com"
              git add $FILE
              git commit -m "Update $FILE ke $LATEST_VER" --quiet || true
              git pull --rebase --quiet || true
              git push --quiet || true

              MSG="⚡ <b>Versi baru tersedia</b>
              ═══════════════════════
              📌 <b>Versi baru:</b> v$LATEST_VER
              📌 <b>Versi lama:</b> $OLD_VER
              📌 <b>Link release:</b> <a href='$RELEASE_URL'>Klik di sini</a>
              ═══════════════════════
             Silakan build kernel..."
            else
              MSG="ℹ️ <b>$NAME tidak ada versi baru</b>
              ═══════════════════════
           📌 <b>Versi terakhir: v$LATEST_VER<b>
              ═══════════════════════
           📌 <b>Link release:</b> <a href='$RELEASE_URL'>Klik di sini</a>"
            fi

            # Kirim notif ke semua chat_id unik
            for CHAT_ID in "${CHAT_IDS[@]}"; do
              curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
                -d chat_id="$CHAT_ID" \
                -d text="$MSG" \
                -d parse_mode="HTML" \
                -d disable_web_page_preview=true
            done
          done

