name: Build luci-app-openclash (Auto Version)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Cek setiap 6 jam

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache last built version
      uses: actions/cache@v4
      with:
        path: last_version.txt
        key: last-version-cache

    - name: Cek versi terbaru dari vernesong/dev
      run: |
        LATEST_VER=$(curl -s https://raw.githubusercontent.com/vernesong/OpenClash/dev/luci-app-openclash/Makefile | grep -oP '(?<=PKG_VERSION:=)[0-9\.]+')
        echo "LATEST_VER=$LATEST_VER" >> $GITHUB_ENV
        echo "Versi terbaru: $LATEST_VER"

        if [ -f last_version.txt ]; then
          LAST_VER=$(cat last_version.txt)
          if [ "$LAST_VER" = "$LATEST_VER" ]; then
            echo "Versi sama ($LATEST_VER), skip build."
            exit 0
          fi
        fi
        echo "$LATEST_VER" > last_version.txt

    - name: Checkout repo tes-rep/OpenClash
      uses: actions/checkout@v4
      with:
        repository: tes-rep/OpenClash
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download OpenWrt SDK 15.05.1
      run: |
        mkdir -p tmp
        curl -SLk --retry 3 "https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2" -o "/tmp/SDK.tar.bz2"
        cd /tmp
        tar xjf SDK.tar.bz2
        mv OpenWrt-SDK-* $GITHUB_WORKSPACE/SDK

    - name: Clone luci-app-openclash dari vernesong/dev
      run: |
       cd $GITHUB_WORKSPACE/SDK/package
       mkdir luci-app-openclash
       cd luci-app-openclash
       git init
       git remote add origin https://github.com/vernesong/OpenClash.git
       git config core.sparseCheckout true
       echo "luci-app-openclash" >> .git/info/sparse-checkout
       git fetch origin dev
       git checkout dev

    - name: Compile po2lmo
      run: |
        cd $GITHUB_WORKSPACE/SDK/package/luci-app-openclash/luci-app-openclash/tools/po2lmo
        make && sudo make install

    - name: Compile luci-app-openclash
      run: |
        cd $GITHUB_WORKSPACE/SDK
        make package/luci-app-openclash/luci-app-openclash/compile V=99

    - name: Ambil file IPK
      run: |
        mkdir release
        find $GITHUB_WORKSPACE/SDK/bin/ -type f -name "luci-app-openclash_*.ipk" -exec cp {} release/luci-app-openclash_${LATEST_VER}.ipk \;

    - name: Upload to Release in tes-rep/OpenClash
      uses: softprops/action-gh-release@v1
      with:
        repository: tes-rep/OpenClash
        tag_name: ${{ env.LATEST_VER }}
        name: "OpenClash ${{ env.LATEST_VER }}"
        files: release/luci-app-openclash_${{ env.LATEST_VER }}.ipk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
