name: Build & Release OpenClash

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repo build (untuk menyimpan last_version.txt)
    - name: Checkout repo build
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0   # perlu full history untuk commit file

    # 2️⃣ Ambil versi terbaru
    - name: Cek versi terbaru
      id: check_version
      run: |
        LATEST_VER=$(curl -s https://raw.githubusercontent.com/vernesong/OpenClash/dev/luci-app-openclash/Makefile | grep -oP '(?<=PKG_VERSION:=)[0-9\.]+')
        echo "LATEST_VER=$LATEST_VER" >> $GITHUB_ENV

        if [ -f last_version.txt ]; then
          LAST_VER=$(cat last_version.txt)
        else
          LAST_VER=""
        fi

        if [ "$LAST_VER" = "$LATEST_VER" ]; then
          echo "SKIP_BUILD=true" >> $GITHUB_ENV
          echo "Versi sama, skip build."
        else
          echo "$LATEST_VER" > last_version.txt
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add last_version.txt
          git commit -m "Update last_version.txt ke $LATEST_VER"
          git push
          echo "SKIP_BUILD=false" >> $GITHUB_ENV
        fi

    # 3️⃣ Ambil 5 commit terakhir dari vernesong/OpenClash
    - name: Ambil 5 commit terakhir
      id: get_commits
      run: |
        git clone --depth 5 --branch dev https://github.com/vernesong/OpenClash.git /tmp/OpenClash
        cd /tmp/OpenClash
        LAST_COMMITS=$(git log -5 --pretty=format:"%h - %s")
        echo "last_commits=$LAST_COMMITS" >> $GITHUB_OUTPUT

    # 4️⃣ Build IPK & APK (hanya jika versi baru)
    - name: Build OpenClash
      if: env.SKIP_BUILD == 'false'
      run: |
        echo "Mulai build IPK & APK..."
        mkdir -p $GITHUB_WORKSPACE/release

        # ==== SDK lama (IPK) ====
        mkdir -p /tmp/sdk_old
        curl -SLk --retry 3 "https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2" -o /tmp/SDK.tar.bz2
        tar -xjf /tmp/SDK.tar.bz2 -C /tmp/sdk_old
        mv /tmp/sdk_old/OpenWrt-SDK-* $GITHUB_WORKSPACE/SDK

        cd $GITHUB_WORKSPACE/SDK/package
        git clone --depth 1 --branch dev --filter=blob:none --sparse https://github.com/vernesong/OpenClash luci-app-openclash
        cd luci-app-openclash && git sparse-checkout set luci-app-openclash

        cd $GITHUB_WORKSPACE/SDK/package/
        pushd luci-app-openclash/luci-app-openclash/tools/po2lmo
        make && sudo make install
        popd

        cd $GITHUB_WORKSPACE/SDK
        make package/luci-app-openclash/luci-app-openclash/compile V=99
        find bin/ -type f -name "luci-app-openclash_*.ipk" -exec cp {} $GITHUB_WORKSPACE/release/luci-app-openclash_${LATEST_VER}_all.ipk \;

        rm -rf $GITHUB_WORKSPACE/SDK /tmp/sdk_old /tmp/SDK.tar.bz2

        # ==== SDK snapshot (APK) ====
        mkdir -p /tmp/sdk_snap
        BASE_URL="https://downloads.openwrt.org/snapshots/targets/x86/64"
        SDK_NAME=$(curl -s $BASE_URL/ | grep -oE 'openwrt-sdk-x86-64[^"]+\.tar\.zst' | head -n 1)
        curl -SLk "$BASE_URL/$SDK_NAME" -o /tmp/SNAPSDK.tar.zst
        tar --zstd -xf /tmp/SNAPSDK.tar.zst -C /tmp/sdk_snap
        mv /tmp/sdk_snap/openwrt-sdk-* $GITHUB_WORKSPACE/SNAPSDK

        cd $GITHUB_WORKSPACE/SNAPSDK/package
        git clone --depth 1 --branch dev --filter=blob:none --sparse https://github.com/vernesong/OpenClash luci-app-openclash
        cd luci-app-openclash && git sparse-checkout set luci-app-openclash

        cd $GITHUB_WORKSPACE/SNAPSDK/package/
        pushd luci-app-openclash/luci-app-openclash/tools/po2lmo
        make && sudo make install
        popd

        cd $GITHUB_WORKSPACE/SNAPSDK
        make defconfig
        make package/luci-app-openclash/luci-app-openclash/compile V=99
        find bin/ -type f -name "luci-app-openclash*.apk" -exec cp {} $GITHUB_WORKSPACE/release/luci-app-openclash-${LATEST_VER}.apk \;

        rm -rf $GITHUB_WORKSPACE/SNAPSDK /tmp/sdk_snap /tmp/SNAPSDK.tar.zst
        echo "Build selesai."

    # 5️⃣ Upload ke Release (hanya jika versi baru)
    - name: Upload ke Release
      if: env.SKIP_BUILD == 'false'
      uses: softprops/action-gh-release@v1
      with:
        repository: tes-rep/OpenClash
        tag_name: v${{ env.LATEST_VER }}
        name: "v${{ env.LATEST_VER }}"
        body: |
          Release OpenClash versi ${{ env.LATEST_VER }}

          5 commit terakhir dari vernesong/OpenClash:
          ${{ steps.get_commits.outputs.last_commits }}
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT3 }}
