name: Build luci-app-openclash uo ke tes-rep

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: tes-rep/OpenClash
        token: ${{ secrets.TARGET_REPO_PAT3 }}
        fetch-depth: 0

    # 2. Cek versi terbaru dari vernesong/dev
    - name: Cek versi terbaru
      id: check_version
      run: |
        # Ambil versi terbaru
        LATEST_VER=$(curl -s https://raw.githubusercontent.com/vernesong/OpenClash/dev/luci-app-openclash/Makefile | grep -oP '(?<=PKG_VERSION:=)[0-9\.]+')
        echo "LATEST_VER=$LATEST_VER" >> $GITHUB_ENV
        echo "Versi terbaru: $LATEST_VER"

        # Baca versi terakhir dari file di repo
        if [ -f $GITHUB_WORKSPACE/last_version.txt ]; then
          LAST_VER=$(cat $GITHUB_WORKSPACE/last_version.txt)
          echo "Versi terakhir di repo: $LAST_VER"
        else
          LAST_VER=""
        fi

        # Bandingkan versi
        if [ "$LAST_VER" = "$LATEST_VER" ]; then
          echo "Versi sama ($LATEST_VER), skip build."
          echo "SKIP_BUILD=true" >> $GITHUB_ENV
        else
          echo "$LATEST_VER" > $GITHUB_WORKSPACE/last_version.txt
          echo "SKIP_BUILD=false" >> $GITHUB_ENV
        fi

    # 3. Commit update last_version.txt ke repo (jika versi baru)
    - name: Commit last_version.txt
      if: env.SKIP_BUILD == 'false'
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add last_version.txt
        git commit -m "Update last_version.txt ke $LATEST_VER"
        git push

    # 4. Checkout repo target
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: tes-rep/OpenClash
        token: ${{ secrets.GITHUB_TOKEN }}

    # 5. ==================== BUILD SDK LAMA (IPK) ====================
    - name: Download & Ekstrak SDK 15.05.1
      run: |
        mkdir -p $GITHUB_WORKSPACE/release
        mkdir -p /tmp/sdk_old
        curl -SLk --retry 3 "https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2" -o /tmp/SDK.tar.bz2
        tar -xjf /tmp/SDK.tar.bz2 -C /tmp/sdk_old
        mv /tmp/sdk_old/OpenWrt-SDK-* $GITHUB_WORKSPACE/SDK

    - name: Clone luci-app-openclash (IPK)
      run: |
        cd $GITHUB_WORKSPACE/SDK/package
        git clone --depth 1 --branch dev --filter=blob:none --sparse https://github.com/vernesong/OpenClash luci-app-openclash
        cd luci-app-openclash && git sparse-checkout set luci-app-openclash

    - name: Compile po2lmo (IPK)
      run: |
        cd $GITHUB_WORKSPACE/SDK/package/
        pushd luci-app-openclash/luci-app-openclash/tools/po2lmo
        make && sudo make install
        popd

    - name: Compile luci-app-openclash (IPK)
      run: |
        cd $GITHUB_WORKSPACE/SDK
        make package/luci-app-openclash/luci-app-openclash/compile V=99
        find bin/ -type f -name "luci-app-openclash_*.ipk" -exec cp {} $GITHUB_WORKSPACE/release/luci-app-openclash_${LATEST_VER}_all.ipk \;

    - name: Bersihkan SDK lama
      run: rm -rf $GITHUB_WORKSPACE/SDK /tmp/sdk_old /tmp/SDK.tar.bz2

    # 6. ==================== BUILD SDK SNAPSHOT (APK) ====================
    - name: Download & Ekstrak SDK Snapshot
      run: |
        mkdir -p /tmp/sdk_snap
        BASE_URL="https://downloads.openwrt.org/snapshots/targets/x86/64"
        SDK_NAME=$(curl -s $BASE_URL/ | grep -oE 'openwrt-sdk-x86-64[^"]+\.tar\.zst' | head -n 1)
        curl -SLk "$BASE_URL/$SDK_NAME" -o /tmp/SNAPSDK.tar.zst
        tar --zstd -xf /tmp/SNAPSDK.tar.zst -C /tmp/sdk_snap
        mv /tmp/sdk_snap/openwrt-sdk-* $GITHUB_WORKSPACE/SNAPSDK

    - name: Clone luci-app-openclash (APK)
      run: |
        cd $GITHUB_WORKSPACE/SNAPSDK/package
        git clone --depth 1 --branch dev --filter=blob:none --sparse https://github.com/vernesong/OpenClash luci-app-openclash
        cd luci-app-openclash && git sparse-checkout set luci-app-openclash

    - name: Compile po2lmo (APK)
      run: |
        cd $GITHUB_WORKSPACE/SNAPSDK/package/
        pushd luci-app-openclash/luci-app-openclash/tools/po2lmo
        make && sudo make install
        popd

    - name: Compile luci-app-openclash (APK)
      run: |
        cd $GITHUB_WORKSPACE/SNAPSDK
        make defconfig
        make package/luci-app-openclash/luci-app-openclash/compile V=99
        find bin/ -type f -name "luci-app-openclash*.apk" -exec cp {} $GITHUB_WORKSPACE/release/luci-app-openclash-${LATEST_VER}.apk \;

    - name: Bersihkan SDK snapshot
      run: rm -rf $GITHUB_WORKSPACE/SNAPSDK /tmp/sdk_snap /tmp/SNAPSDK.tar.zst

    # 7. Upload ke Release
    - name: Upload ke Release
      uses: softprops/action-gh-release@v1
      with:
        repository: tes-rep/OpenClash
        tag_name: v${{ env.LATEST_VER }}
        name: "v${{ env.LATEST_VER }}"
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT3 }}
