name: Build luci-app-openclash ke tes-rep5

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      skip_build: ${{ steps.setvar.outputs.skip_build }}
      latest_ver: ${{ steps.setvar.outputs.latest_ver }}
    steps:
      - name: Checkout repo build
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Cek versi terbaru
        id: setvar
        run: |
          LATEST_VER=$(curl -s https://raw.githubusercontent.com/vernesong/OpenClash/dev/luci-app-openclash/Makefile | grep -oP '(?<=PKG_VERSION:=)[0-9\.]+')
          echo "latest_ver=$LATEST_VER" >> $GITHUB_OUTPUT
          echo "Versi terbaru: $LATEST_VER"

          if [ -f last_version.txt ]; then
            LAST_VER=$(cat last_version.txt)
          else
            LAST_VER=""
          fi

          if [ "$LAST_VER" = "$LATEST_VER" ]; then
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "$LATEST_VER" > last_version.txt
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add last_version.txt
            git commit -m "Update last_version.txt ke $LATEST_VER" --quiet || true
            git pull --rebase --quiet || true
            git push --quiet || true
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Notif Telegram versi terbaru
        run: |
          VER="v${{ steps.setvar.outputs.latest_ver }}"
          BASE_URL="https://github.com/tes-rep/OpenClash/releases/download/$VER"
          RELEASE_URL="https://github.com/tes-rep/OpenClash/releases/tag/$VER"

          # Ambil versi lama
          if [ -f last_version.txt ]; then
            OLD_VER=$(cat last_version.txt)
          else
            OLD_VER="tidak tersedia"
          fi

          if [[ "${{ steps.setvar.outputs.skip_build }}" == "true" ]]; then
          # Versi sama dengan terakhir
          STATUS="ℹ️ <b>Tidak ada versi baru</b>"
          HEADER="Versi terakhir: <b>$VER</b>"
          MSG=$(printf "%s\n%s\n\n═══════════════════════\n🔗 <b>Release:</b> <a href=\"%s\">Klik di sini</a>\n📦 <b>IPK:</b> <a href=\"%s/luci-app-openclash_%s_all.ipk\">Download</a>\n📱 <b>APK:</b> <a href=\"%s/luci-app-openclash-%s.apk\">Download</a>" \
            "$STATUS" \
            "$HEADER" \
            "$RELEASE_URL" \
            "$BASE_URL" "$VER" \
            "$BASE_URL" "$VER")
          else
          # Versi baru terdeteksi → notif build dimulai
            MSG=$(printf "⚡ <b>Build OpenClash dimulai...</b>\n═══════════════════════\n📌 <b>Versi baru:</b> %s\n📌 <b>Versi lama:</b> %s\n═══════════════════════\nHarap tunggu beberapa menit 🚀" \
              "$VER" \
              "$OLD_VER")
          fi

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MSG" \
            -d parse_mode="HTML"
            -d disable_web_page_preview=true


  build:
    needs: check-version
    if: needs.check-version.outputs.skip_build == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ipk, apk]

    steps:
      - name: Catat waktu mulai
        run: |
          echo "BUILD_START=$(date +%s)" >> $GITHUB_ENV
          echo "BUILD_START_HUMAN=$(TZ=Asia/Jakarta date '+%Y-%m-%d %H:%M:%S WIB')" >> $GITHUB_ENV

      - name: Checkout repo release
        uses: actions/checkout@v4
        with:
          repository: tes-rep/OpenClash
          token: ${{ secrets.TARGET_REPO_PAT3 }}

      # ----------------- IPK Build -----------------
      - name: Cache SDK lama
        if: matrix.target == 'ipk'
        id: cache_ipk
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/SDK
          key: sdk-old-${{ needs.check-version.outputs.latest_ver }}

      - name: Download & Ekstrak SDK 15.05.1
        if: matrix.target == 'ipk' && steps.cache_ipk.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/sdk_old
          curl -SLk --retry 3 "https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2" -o /tmp/SDK.tar.bz2
          tar -xjf /tmp/SDK.tar.bz2 -C /tmp/sdk_old
          mv /tmp/sdk_old/OpenWrt-SDK-* $GITHUB_WORKSPACE/SDK

      - name: Clone luci-app-openclash IPK
        if: matrix.target == 'ipk'
        run: |
          cd $GITHUB_WORKSPACE/SDK/package
          if [ -d "luci-app-openclash" ]; then
            cd luci-app-openclash
            git fetch --depth 1 origin dev
            git reset --hard origin/dev
          else
            git clone --depth 1 --branch dev --filter=blob:none --sparse https://github.com/vernesong/OpenClash luci-app-openclash
            cd luci-app-openclash && git sparse-checkout set luci-app-openclash
          fi

      - name: Compile po2lmo (IPK)
        if: matrix.target == 'ipk'
        run: |
          cd $GITHUB_WORKSPACE/SDK/package/luci-app-openclash/luci-app-openclash/tools/po2lmo
          make && sudo make install

      - name: Compile luci-app-openclash (IPK)
        if: matrix.target == 'ipk'
        run: |
          cd $GITHUB_WORKSPACE/SDK
          make package/luci-app-openclash/luci-app-openclash/compile V=99
          mkdir -p $GITHUB_WORKSPACE/release
          find bin/ -type f -name "luci-app-openclash_*.ipk" -exec cp {} $GITHUB_WORKSPACE/release/luci-app-openclash_${{ needs.check-version.outputs.latest_ver }}_all.ipk \;

      # ----------------- APK Build -----------------
      - name: Cache SDK snapshot
        if: matrix.target == 'apk'
        id: cache_apk
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/SNAPSDK
          key: sdk-snap-${{ needs.check-version.outputs.latest_ver }}

      - name: Download & Ekstrak SDK Snapshot
        if: matrix.target == 'apk' && steps.cache_apk.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/sdk_snap
          BASE_URL="https://downloads.openwrt.org/snapshots/targets/x86/64"
          SDK_NAME=$(curl -s $BASE_URL/ | grep -oE 'openwrt-sdk-x86-64[^"]+\.tar\.zst' | head -n 1)
          curl -SLk "$BASE_URL/$SDK_NAME" -o /tmp/SNAPSDK.tar.zst
          tar --zstd -xf /tmp/SNAPSDK.tar.zst -C /tmp/sdk_snap
          mv /tmp/sdk_snap/openwrt-sdk-* $GITHUB_WORKSPACE/SNAPSDK

      - name: Clone luci-app-openclash (APK)
        if: matrix.target == 'apk'
        run: |
          cd $GITHUB_WORKSPACE/SNAPSDK/package
          if [ -d "luci-app-openclash" ]; then
            cd luci-app-openclash
            git fetch --depth 1 origin dev
            git reset --hard origin/dev
          else
            git clone --depth 1 --branch dev --filter=blob:none --sparse https://github.com/vernesong/OpenClash luci-app-openclash
            cd luci-app-openclash && git sparse-checkout set luci-app-openclash
          fi

      - name: Compile po2lmo (APK)
        if: matrix.target == 'apk'
        run: |
          cd $GITHUB_WORKSPACE/SNAPSDK/package/luci-app-openclash/luci-app-openclash/tools/po2lmo
          make && sudo make install

      - name: Compile luci-app-openclash (APK)
        if: matrix.target == 'apk'
        run: |
          cd $GITHUB_WORKSPACE/SNAPSDK
          make defconfig
          make package/luci-app-openclash/luci-app-openclash/compile V=99
          mkdir -p $GITHUB_WORKSPACE/release
          find bin/ -type f -name "luci-app-openclash*.apk" -exec cp {} $GITHUB_WORKSPACE/release/luci-app-openclash-${{ needs.check-version.outputs.latest_ver }}.apk \;

      # ----------------- Upload Release -----------------
      - name: Upload ke Release
        id: upload_release
        uses: softprops/action-gh-release@v1
        with:
          repository: tes-rep/OpenClash
          tag_name: v${{ needs.check-version.outputs.latest_ver }}
          name: "v${{ needs.check-version.outputs.latest_ver }}"
          body: |
            ## OpenClash v${{ needs.check-version.outputs.latest_ver }}
            **Changelog:**
            - Update versi terbaru dari vernesong/dev
            - **Full Changelog**: https://github.com/vernesong/OpenClash/commits/dev/
            - Build IPK & APK
          files: release/*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_PAT3 }}

      # ----------------- Telegram Notif -----------------
      
      - name: Notif Telegram Build Selesai
        if: success()
        run: |
          BUILD_END=$(date +%s)
          DURATION=$((BUILD_END - BUILD_START))
          MIN=$((DURATION / 60))
          SEC=$((DURATION % 60))

          VER="${{ needs.check-version.outputs.latest_ver }}"
          RELEASE_URL="https://github.com/tes-rep/OpenClash/releases/tag/v$VER"
          BASE_URL="https://github.com/tes-rep/OpenClash/releases/download/$VER"

          # Ambil versi lama
          if [ -f last_version.txt ]; then
            OLD_VER=$(cat last_version.txt)
          else
          OLD_VER="tidak tersedia"
          fi

          IPK_FILE="luci-app-openclash_${VER}_all.ipk"
          APK_FILE="luci-app-openclash-${VER}.apk"

          MSG=$(printf "✅ Build OpenClash Selesai!\n═══════════════════════\nVersi baru: %s\nVersi lama: %s\n═══════════════════════\n🕒 Start: %s\n⏱ Durasi: %dm %ds\n═══════════════════════\n🔗 Release: <a href=\"%s\">Klik di sini</a>\n📦 IPK: <a href=\"%s/%s\">Download</a>\n📱 APK: <a href=\"%s/%s\">Download</a>" \
            "$VER" \
            "$OLD_VER" \
            "$BUILD_START_HUMAN" \
            "$MIN" "$SEC" \
            "$RELEASE_URL" \
            "$BASE_URL" "$IPK_FILE" \
            "$BASE_URL" "$APK_FILE")
            

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MSG" \
            -d parse_mode="HTML"
