name: Tes Notif Telegram

on:
  workflow_dispatch:

jobs:
  test-notif:
    runs-on: ubuntu-latest
    steps:
      - name: Kirim pesan tes 1 (info)
        run: |
          MSG=$(printf "ℹ️ <b>Tidak ada versi baru</b>\n\n📌 Versi terakhir: <b>v0.46.064</b>\n🔗 <a href='https://github.com/tes-rep/OpenClash/releases/tag/v0.46.064'>Release</a>")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MSG" \
            -d parse_mode="HTML"

      - name: Kirim pesan tes 2 (build dimulai)
        run: |
          MSG=$(printf "⚡ <b>Build OpenClash dimulai...</b>\n\n📌 Versi baru: <b>v0.46.065</b>\n📌 Versi lama: <b>v0.46.064</b>\n\nHarap tunggu beberapa menit 🚀")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MSG" \
            -d parse_mode="HTML"

      - name: Kirim pesan tes 3 (build selesai)
        run: |
          OLD_VER="v0.46.064"
          NEW_VER="v0.46.065"

          MSG=$(printf "✅ <b>Build OpenClash Selesai!</b>\n═══════════════════════\n📌 Versi baru: <b>%s</b>\n📌 Versi lama: <b>%s</b>\n🕒 Start: 2025-08-18 12:10:33 WIB\n⏱ Durasi: 3m 42s\n═══════════════════════\n🔗 <a href='https://github.com/tes-rep/OpenClash/releases/tag/%s'>Release</a>\n📦 <a href='https://github.com/tes-rep/OpenClash/releases/download/%s/luci-app-openclash_%s_all.ipk'>IPK</a>\n📱 <a href='https://github.com/tes-rep/OpenClash/releases/download/%s/luci-app-openclash-%s.apk'>APK</a>" \
            "$NEW_VER" \
            "$OLD_VER" \
            "$NEW_VER" \
            "$NEW_VER" "$NEW_VER" \
            "$NEW_VER" "$NEW_VER")

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MSG" \
            -d parse_mode="HTML"
