name: TEST v7 - Copy With Different Source and Target Paths

on:
  workflow_dispatch:
    inputs:
      kernel_url:
        description: 'URL file arsip driver (tar.gz, zip, zst) – isi "none" untuk skip download'
        required: false
        default: ''
        type: string

      repo_clone_url:
        description: 'Repo GitHub driver (contoh: https://github.com/unifreq/linux-5.15.y.git)'
        required: false
        default: 'https://github.com/unifreq/linux-5.15.y.git'
        type: string

      driver_type:
        description: 'Path sumber (contoh: drivers/net/wireless/uwe5623)'
        required: true
        default: 'drivers/net/wireless/uwe5623'
        type: string

      target_path:
        description: 'Path tujuan di repo target (contoh: drivers/staging/uwe5623)'
        required: true
        default: 'drivers/staging/uwe5623'
        type: string

      target_repo:
        description: 'Target repo GitHub (contoh: houjie/linux-openwrt)'
        required: true
        type: string

      target_branch:
        description: 'Target branch di repo tujuan'
        required: false
        default: coba
        type: string

jobs:
  sync_driver:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.TARGET_REPO_PAT }}

    steps:
      - name: Normalize Target Repo
        id: fixrepo
        run: |
          repo="${{ github.event.inputs.target_repo }}"
          if [[ "$repo" == https://github.com/* ]]; then
            repo="${repo#https://github.com/}"
            repo="${repo%/}"
          fi
          echo "normalized_repo=$repo" >> $GITHUB_OUTPUT

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 unzip megatools zstd patch
          python3 -m pip install --upgrade gdown

      - name: Download Driver Archive
        if: ${{ github.event.inputs.kernel_url != '' && github.event.inputs.kernel_url != 'none' }}
        run: |
          mkdir -p kernel-archive-download
          url="${{ github.event.inputs.kernel_url }}"
          if [[ "$url" =~ mega\.nz ]]; then
            megadl --path=kernel-archive-download "$url"
          elif [[ "$url" =~ drive.google.com ]]; then
            FILE_ID=$(echo "$url" | grep -oP '(?<=/d/)[^/]+')
            [ -z "$FILE_ID" ] && FILE_ID=$(echo "$url" | grep -oP '(?<=id=)[^&]+')
            [ -z "$FILE_ID" ] && { echo "Invalid Google Drive URL"; exit 1; }
            cd kernel-archive-download && gdown "https://drive.google.com/uc?id=$FILE_ID" && cd ..
          else
            aria2c -q -x 16 -s 16 -d kernel-archive-download "$url"
          fi

      - name: Extract Archive
        if: ${{ github.event.inputs.kernel_url != '' && github.event.inputs.kernel_url != 'none' }}
        run: |
          mkdir -p kernel-extracted
          file_path=$(ls kernel-archive-download/* | head -n 1)
          mv "$file_path" kernel-archive
          type=$(file kernel-archive)
          if [[ "$type" =~ Zstandard ]]; then
            tar --use-compress-program=unzstd -xvf kernel-archive -C kernel-extracted
          elif [[ "$type" =~ gzip ]]; then
            tar -xzf kernel-archive -C kernel-extracted
          elif [[ "$type" =~ Zip ]]; then
            unzip -o kernel-archive -d kernel-extracted
          elif [[ "$type" =~ POSIX.*tar ]]; then
            tar -xf kernel-archive -C kernel-extracted
          else
            echo "Unsupported archive format"
            exit 1
          fi

      - name: Clone Driver Repo
        if: ${{ github.event.inputs.kernel_url == '' || github.event.inputs.kernel_url == 'none' }}
        run: |
          git clone --depth=1 "${{ github.event.inputs.repo_clone_url }}" driver-clone

      - name: Clone Target Repo
        run: |
          git clone https://x-access-token:${PAT}@github.com/${{ steps.fixrepo.outputs.normalized_repo }}.git target-repo
          cd target-repo
          git checkout ${{ github.event.inputs.target_branch }} || git checkout -b ${{ github.event.inputs.target_branch }}

      - name: Copy Driver from Repo (custom path)
        if: ${{ github.event.inputs.kernel_url == '' || github.event.inputs.kernel_url == 'none' }}
        run: |
          src="driver-clone/${{ github.event.inputs.driver_type }}"
          dst="target-repo/${{ github.event.inputs.target_path }}"
          mkdir -p "$(dirname "$dst")"
          cp -r "$src" "$(dirname "$dst")/"

      - name: Copy Driver from Archive (custom path)
        if: ${{ github.event.inputs.kernel_url != '' && github.event.inputs.kernel_url != 'none' }}
        run: |
          cd kernel-extracted
          entries=(*/)
          if [ ${#entries[@]} -eq 1 ]; then
            cd "${entries[0]}"
          fi
          src="${{ github.event.inputs.driver_type }}"
          dst="../../target-repo/${{ github.event.inputs.target_path }}"
          mkdir -p "$(dirname "$dst")"
          cp -r "$src" "$(dirname "$dst")/"
          cd ../..

      - name: Commit and Push
        run: |
          cd target-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "${{ github.event.inputs.target_path }}"
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync driver to ${{ github.event.inputs.target_path }}"
            git push -u origin ${{ github.event.inputs.target_branch }}
            fi
