name: TEST v12 - Full or Partial Sync

on:
  workflow_dispatch:
    inputs:
      rootfs_url:
        description: 'URL file arsip driver (tar.gz, zip, zst, dll) atau kosong jika pakai repo'
        required: false
        default: ''
        type: string
      type_file:
        description: 'Ekstensi file (misal: zip, tar.gz, img)'
        required: false
        default: ''
        type: string
      repo_clone_url:
        description: 'Repo GitHub sumber (contoh: https://github.com/unifreq/linux-5.15.y.git)'
        required: false
        default: 'https://github.com/unifreq/linux-5.15.y.git'
        type: string
      driver_type:
        description: 'Path sumber, pisahkan dengan koma jika banyak (contoh: drivers/net/wireless,fs/ntfs3)'
        required: false
        default: ''
        type: string
      target_path:
        description: 'Path tujuan, pisahkan dengan koma sesuai urutan driver_type (contoh: package/kernel/wifi,package/kernel/ntfs3)'
        required: false
        default: ''
        type: string
      target_repo:
        description: 'Target repo GitHub (contoh: houjie/linux-openwrt)'
        required: true
        type: string
      target_branch:
        description: 'Target branch di repo tujuan'
        required: false
        default: coba
        type: string
      token_option:
        description: 'Pilih token GitHub (PAT)'
        required: true
        default: tes-rep
        type: choice
        options:
          - tes-rep
          - DIRGHA80
          - HOUJIE80

jobs:
  sync_driver:
    runs-on: ubuntu-24.04

    steps:
      - name: Set Token from Input
        id: choose_token
        run: |
          case "${{ github.event.inputs.token_option }}" in
            tes-rep)
              echo "PAT=${{ secrets.TARGET_REPO_INI }}" >> $GITHUB_ENV
              ;;
            DIRGHA80)
              echo "PAT=${{ secrets.TARGET_REPO_DIRGHA80 }}" >> $GITHUB_ENV
              ;;
            HOUJIE80)
              echo "PAT=${{ secrets.TARGET_REPO_HOUJIE80 }}" >> $GITHUB_ENV
              ;;
            *)
              echo "::error ::Pilihan token tidak valid!"
              exit 1
              ;;
          esac

      - name: Normalize Target Repo
        id: fixrepo
        run: |
          repo="${{ github.event.inputs.target_repo }}"
          if [[ "$repo" == https://github.com/* ]]; then
            repo="${repo#https://github.com/}"
            repo="${repo%/}"
          fi
          echo "normalized_repo=$repo" >> $GITHUB_OUTPUT

      - name: Validate Inputs
        if: ${{ github.event.inputs.driver_type != '' && github.event.inputs.target_path == '' }}
        run: |
          echo "::error ::'target_path' wajib diisi jika 'driver_type' ditentukan."
          exit 1

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 unzip zstd wget npm jq
          sudo pip3 install gdown
          sudo pip3 install git+https://github.com/Juvenal-Yescas/mediafire-dl
          wget https://mega.nz/linux/repo/xUbuntu_24.04/amd64/megacmd-xUbuntu_24.04_amd64.deb && sudo apt install "$PWD/megacmd-xUbuntu_24.04_amd64.deb"

      - name: Download file ${{ github.event.inputs.type_file }}
        if: ${{ github.event.inputs.rootfs_url != '' }}
        run: |
          mkdir -p build
          echo "[🔍] Mendeteksi sumber dari: ${{ github.event.inputs.rootfs_url }}"

          if echo "${{ github.event.inputs.rootfs_url }}" | grep -q "drive."; then
            echo "[🌐] Sumber: Google Drive"
            if echo "${{ github.event.inputs.rootfs_url }}" | awk -F "/" '{print $6}' | grep -q .; then
              link_gdrive=$(echo "${{ github.event.inputs.rootfs_url }}" | awk -F "/" '{print $6}')
            else
              link_gdrive=$(echo "${{ github.event.inputs.rootfs_url }}" | awk -F "/" '{print $4}' | awk -F "?id=" '{print $2}' | awk -F "&export" '{print $1}')
            fi
            echo "[⬇️] Mengunduh dari Google Drive: ID $link_gdrive"
            sudo gdown "$link_gdrive" -O build/file.${{ github.event.inputs.type_file }}

          elif echo "${{ github.event.inputs.rootfs_url }}" | grep -q "mediafire.com"; then
            echo "[🌐] Sumber: MediaFire"
            sudo mediafire-dl "${{ github.event.inputs.rootfs_url }}" -o build/file.${{ github.event.inputs.type_file }}

          elif echo "${{ github.event.inputs.rootfs_url }}" | grep -q "mega.nz"; then
            echo "[🌐] Sumber: MEGA.nz"
            file_mega=$(sudo mega-get "${{ github.event.inputs.rootfs_url }}" | awk -F: '{print $2}' | tr -d ' ')
            sudo mv "${file_mega}" "build/file.${{ github.event.inputs.type_file }}"

          else
            echo "[🌐] Sumber: URL langsung"
            sudo wget --no-check-certificate "${{ github.event.inputs.rootfs_url }}" -O build/file.${{ github.event.inputs.type_file }}
          fi

      - name: Extract Archive
        if: ${{ github.event.inputs.rootfs_url != '' && github.event.inputs.type_file != '' }}
        run: |
          mkdir -p extracted
          file_type=$(file build/file.${{ github.event.inputs.type_file }})

          if [[ "$file_type" =~ "gzip compressed" ]]; then
            tar -xzf build/file.${{ github.event.inputs.type_file }} -C extracted
          elif [[ "$file_type" =~ "Zip archive data" ]]; then
            unzip -o build/file.${{ github.event.inputs.type_file }} -d extracted
          elif [[ "$file_type" =~ "Zstandard compressed" ]]; then
            tar --use-compress-program=unzstd -xf build/file.${{ github.event.inputs.type_file }} -C extracted
          elif [[ "$file_type" =~ "XZ compressed data" ]]; then
            tar -xJf build/file.${{ github.event.inputs.type_file }} -C extracted
          elif [[ "$file_type" =~ "POSIX tar archive" ]]; then
            tar -xf build/file.${{ github.event.inputs.type_file }} -C extracted
          else
            echo "Unsupported archive format or not an archive, skipping extraction."
          fi

      - name: Clone Driver Repo
        if: ${{ github.event.inputs.rootfs_url == '' }}
        run: |
          git clone --depth=1 "${{ github.event.inputs.repo_clone_url }}" driver-clone

      - name: Clone Target Repo
        run: |
          git clone https://x-access-token:${{ env.PAT }}@github.com/${{ steps.fixrepo.outputs.normalized_repo }}.git target-repo
          cd target-repo
          git checkout ${{ github.event.inputs.target_branch }} || git checkout -b ${{ github.event.inputs.target_branch }}

      - name: Copy All (Repo mode)
        if: ${{ github.event.inputs.rootfs_url == '' && github.event.inputs.driver_type == '' }}
        run: |
          rsync -a --exclude='.git' driver-clone/ target-repo/

      - name: Copy All (Archive mode)
        if: ${{ github.event.inputs.rootfs_url != '' && github.event.inputs.driver_type == '' }}
        run: |
          cd extracted
          entry_count=$(find . -mindepth 1 -maxdepth 1 -type d | wc -l)
          if [ "$entry_count" -eq 1 ]; then
            cd "$(find . -mindepth 1 -maxdepth 1 -type d)"
          fi
          rsync -a --exclude='.git' ./ ../../target-repo/
          cd ../..

      - name: Copy Multi Patch (Repo mode)
        if: ${{ github.event.inputs.rootfs_url == '' && github.event.inputs.driver_type != '' }}
        run: |
          IFS=',' read -ra srcs <<< "${{ github.event.inputs.driver_type }}"
          IFS=',' read -ra dsts <<< "${{ github.event.inputs.target_path }}"

          if [ ${#srcs[@]} -ne ${#dsts[@]} ]; then
            echo "::error ::Jumlah driver_type dan target_path tidak sama!"
            exit 1
          fi

          for i in "${!srcs[@]}"; do
            src="driver-clone/${srcs[$i]}"
            dst="target-repo/${dsts[$i]}"

            if [ -d "$src" ]; then
              echo "[📂] Copy folder $src → $dst"
              mkdir -p "$dst"
              rsync -a --exclude='.git' "$src/" "$dst/"
            elif [ -f "$src" ]; then
              echo "[📄] Copy file $src → $dst"
              mkdir -p "$(dirname "$dst")"
              cp "$src" "$dst"
            else
              echo "::warning ::Path $src tidak ditemukan!"
            fi
          done

      - name: Copy Multi Patch (Archive mode)
        if: ${{ github.event.inputs.rootfs_url != '' && github.event.inputs.driver_type != '' }}
        run: |
          cd extracted
          entry_count=$(find . -mindepth 1 -maxdepth 1 -type d | wc -l)
          if [ "$entry_count" -eq 1 ]; then
            cd "$(find . -mindepth 1 -maxdepth 1 -type d)"
          fi

          IFS=',' read -ra srcs <<< "${{ github.event.inputs.driver_type }}"
          IFS=',' read -ra dsts <<< "${{ github.event.inputs.target_path }}"

          if [ ${#srcs[@]} -ne ${#dsts[@]} ]; then
            echo "::error ::Jumlah driver_type dan target_path tidak sama!"
            exit 1
          fi

          for i in "${!srcs[@]}"; do
            src="${srcs[$i]}"
            dst="../../target-repo/${dsts[$i]}"

            if [ -d "$src" ]; then
              echo "[📂] Copy folder $src → $dst"
              mkdir -p "$dst"
              rsync -a --exclude='.git' "$src/" "$dst/"
            elif [ -f "$src" ]; then
              echo "[📄] Copy file $src → $dst"
              mkdir -p "$(dirname "$dst")"
              cp "$src" "$dst"
            else
              echo "::warning ::Path $src tidak ditemukan!"
            fi
          done

          cd ../..

      - name: Commit and Push
        run: |
          cd target-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "✅ Tidak ada perubahan yang perlu dikomit."
          else
            git commit -m "Sync driver(s) or full source from upstream"
            git log -1 --oneline
            git push -u origin ${{ github.event.inputs.target_branch }}
          fi

      - name: List Synced Files
        run: |
          echo "📦 Daftar file di target-repo:"
          cd target-repo
          find . -type f | sort
